OD-251 [Feature] Filter list updates
Fliplet/fliplet-widget-dynamic-lists pull request #450
Opened 2020-12-01 12:38 UTC by AndrRyaz

@sofiiakvasnevska 
## Issue
OD-267 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-267
## Description
Update filter list fields
## Screenshots/screencasts
https://screencast-o-matic.com/watch/cYlVlANQxj
## Backward compatibility
This change is fully backward compatible.
## Reviewers
@upplabs-alex-levchenko

2020-12-01 15:40 UTC, tonytlwu requested changes
Branch out of date

2020-12-01 15:45 UTC, AndrRyaz commented
@tonytlwu updated

2020-12-01 16:21 UTC, tonytlwu commented
Issue description mentioned OD-267 and that's incorrect.

The 3rd acceptance criterion and scenario 4 described that the field label should say `(Field)` when none is selected. The sreencast showed that when none is selected, it doesn't say `(Field)`.

2020-12-01 16:49 UTC, AndrRyaz commented
@tonytlwu fixed

2020-12-01 16:51 UTC, AndrRyaz commented
@tonytlwu updated 
https://screencast-o-matic.com/watch/cYlVD7NXXS

2020-12-01 17:46 UTC, tonytlwu requested changes

2020-12-01 17:46 UTC, tonytlwu commented on templates/interface/filter-panels.interface.hbs
> -        <span class="logic">{{logicLabel}}</span>
The code that is used to populate this isn't needed any more. See interface.js.

2020-12-02 10:12 UTC, AndrRyaz commented
@tonytlwu updated and removed the code that we don't need anymore

2020-12-02 15:27 UTC, tonytlwu requested changes
https://github.com/Fliplet/fliplet-widget-dynamic-lists/blob/4dc28a8cf2ace39f8d8e0400d953430ece07087b/js/interface.js#L248 isn't needed either. It doesn't look like the review of unused code is thorough enough.

2020-12-03 10:01 UTC, AndrRyaz commented
@tonytlwu fixed and remove unused code, next time i will be more attentive

2020-12-03 10:10 UTC, AndrRyaz commented
@tonytlwu fixed and remove unused code, next time i will be more attentive

2020-12-03 10:34 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Studio users configuring LFD prefilters
Verify: Filters can be correctly set up and loaded

2020-12-03 10:37 UTC, merged