OD-106 [Feature] Users will see selected filters that they have select in the filter overlay
Fliplet/fliplet-widget-dynamic-lists pull request #488
Opened 2021-01-14 09:02 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-106

## Description
We have added a new function into the utils.js file to handle when we should show users active filters.

## Screenshots/screencasts
https://share.getcloudapp.com/YEuQ2YPk

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko @ivandevupp

2021-01-15 17:02 UTC, tonytlwu requested changes

2021-01-15 17:02 UTC, tonytlwu commented on js/utils.js
> +    $filtersGroup.on('click', '.hidden-filter-controls-filter.mixitup-control-active', options, onActiveFilterClick);
This is possibly why you were having problem with multiple click events. The filter group is always on the page, which means there's no need to add the event listeners every time the active filters are updated. What I've suggested here is to add the event listeners to the filter options, which avoids having duplicated event listeners on a single element.

```suggestion
    $filtersGroup.find('.hidden-filter-controls-filter.mixitup-control-active').on('click', function() {
      onActiveFilterClick(options);
    });
```

2021-01-15 17:02 UTC, tonytlwu commented on js/utils.js
> +   * @return {void} this function doesn't return anything it adds active filters directly into the DOM of the page
You can just leave it out.

```suggestion
```

2021-01-18 09:06 UTC, YaroslavOvdii commented
@tonytlwu added suggestions

2021-01-19 10:56 UTC, tonytlwu requested changes

2021-01-19 10:56 UTC, tonytlwu commented on js/utils.js
> +    var activeFiltersElements = $.map($selectedFilters, function(filter) {
```suggestion
    var activeFilterElements = $.map($selectedFilters, function(filter) {
```

2021-01-19 10:56 UTC, tonytlwu commented on js/utils.js
> +    var $selectedFilters = $container.find('[data-filter-group] .mixitup-control-active');
This was not done

2021-01-19 11:28 UTC, YaroslavOvdii commented
@tonytlwu Renamed variables

2021-01-19 11:42 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: High
Affected: LFD users with filters enabled
Verify: LFD filters are working as expected

Squash and merge: Show active filters when filters are selected in overlay

2021-01-19 13:22 UTC, merged