OD-90 [Feature] Users will be able to see amount of the selected filters
Fliplet/fliplet-widget-dynamic-lists pull request #491
Opened 2021-01-15 07:53 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-90

## Description
We have added a function that counts the amount of the selected filters.

## Screenshots/screencasts
https://share.getcloudapp.com/ApuG0mbl

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@AndrRyaz @ivandevupp

2021-01-15 16:19 UTC, tonytlwu requested changes

2021-01-15 16:19 UTC, tonytlwu commented on js/utils.js
> +      showSelectedFiltersAmount: showSelectedFiltersAmount
```suggestion
      updateFilterSelectionCount: updateFilterSelectionCount
```

2021-01-15 16:19 UTC, tonytlwu commented on js/utils.js
> +    if (!options.filtersInOverlay || !options.$target.length) {
```suggestion
    if (!options.filtersInOverlay || !options.$target || !options.$target.length) {
```

2021-01-15 16:19 UTC, tonytlwu commented on templates/build/agenda-filters.build.hbs
> +            <span class="panel-title-amount"></span>
```suggestion
            <span class="filter-selection-count"></span>
```

2021-01-15 16:19 UTC, tonytlwu commented on js/utils.js
> +    var activeFiltersAmount = $filterPanel.find('[data-filter-group] .mixitup-control-active').length;
```suggestion
    var activeFiltersSelected = $filterPanel.find('[data-filter-group] .mixitup-control-active').length;
```

2021-01-15 16:19 UTC, tonytlwu commented on js/utils.js
> +    var $filtersAmount = $filterPanel.find('.panel-heading .panel-title .panel-title-amount');
```suggestion
    var $count = $filterPanel.find('.panel-heading .panel-title .panel-title-amount');
```

2021-01-15 16:35 UTC, tonytlwu commented
@YaroslavOvdii I updated my suggestions to use the phrase "active filter" to match the terminologies used in https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/488

2021-01-18 09:15 UTC, YaroslavOvdii commented
@tonytlwu Added suggestions

2021-01-19 10:52 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: High
Affected: LFD users with filters enabled
Verify: LFD filters work correctly

Squash and merge: Add active filter count to filter overlays

2021-01-19 11:22 UTC, merged