OD-499 [Fix] Users will be able to open simple list detail view
Fliplet/fliplet-widget-dynamic-lists pull request #582
Opened 2021-05-13 15:18 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-499

## Description
Added fallback when a file isn't a string but an object

## Screenshots/screencasts
https://share.getcloudapp.com/mXupL7Qb

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko @AndrRyaz

2021-05-17 16:25 UTC, tonytlwu requested changes

2021-05-17 16:25 UTC, tonytlwu commented on js/utils.js
> +          var matchedFileUrl = url.match(/v1\/media\/files\/([0-9]+)/);
Can we not use this?

```suggestion
          return Fliplet.Media.getIdFromRemoteUrl(url);
```

2021-05-18 08:22 UTC, YaroslavOvdii commented on js/utils.js
> +          var matchedFileUrl = url.match(/v1\/media\/files\/([0-9]+)/);
@tonytlwu fixed

2021-05-18 10:29 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: High
Affected: LFDs with files and images (detail view/thumbnail)
Verify: Files an images are all working as expected

Squash and merge: Use PR title

2021-05-19 12:19 UTC, merged