OD-572 [ADD] added transtation to LFD
Fliplet/fliplet-widget-dynamic-lists pull request #616
Opened 2021-09-27 08:11 UTC by OleksandrLavrynenko

@sofiiakvasnevska @inna-bieshulia

OD-572 https://weboo.atlassian.net/browse/OD-572

## Description
Added user translations in LFD components

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2021-09-28 23:02 UTC, tonytlwu requested changes

2021-09-30 08:56 UTC, tonytlwu approved these changes
@sofiiakvasnevska @inna-bieshulia Translation looks ready. This can be tested once API is ready.

2022-04-20 12:39 UTC, skrupnyk commented on templates/build/news-feed-base.build.hbs
>        <input type="search" name="search-feed" class="form-control search-feed focus-outline" tabindex="0" placeholder="Search..." required >
placeholder="{{T "widgets.list.dynamic.search.placeholder"}}"

2022-04-20 12:39 UTC, skrupnyk commented on templates/build/simple-list-base.build.hbs
>        <input type="search" name="search-feed" class="form-control search-feed focus-outline" tabindex="0" placeholder="Search..." required >
placeholder="{{T "widgets.list.dynamic.search.placeholder"}}"

2022-04-20 12:39 UTC, skrupnyk commented on templates/build/small-card-base.build.hbs
>        <input type="search" name="search-feed" class="form-control search-feed focus-outline" tabindex="0" placeholder="Search..." required >
placeholder="{{T "widgets.list.dynamic.search.placeholder"}}"

2022-04-20 12:43 UTC, skrupnyk reviewed
https://github.com/Fliplet/fliplet-widget-dynamic-lists/blob/60ff1610f7476ae9751221cfa621f0bd826c19a6/js/layout-javascript/news-feed-code.js#L2669

T("widgets.list.dynamic.comments.title")

2022-04-20 12:45 UTC, skrupnyk reviewed
https://github.com/Fliplet/fliplet-widget-dynamic-lists/blob/60ff1610f7476ae9751221cfa621f0bd826c19a6/js/layout-javascript/simple-list-code.js#L2616

T("widgets.list.dynamic.comments.title")

2022-04-20 12:49 UTC, skrupnyk commented on translation.json
> +          "offline": "You are offline",
Add `"placeholder": "Type comment",`

2022-04-20 12:54 UTC, skrupnyk commented on templates/build/news-feed-base.build.hbs
>        <textarea class="form-control" rows="1" placeholder="Type comment" data-comment-body></textarea>
`placeholder="{{T "widgets.list.dynamic.comments.placeholder"}}"`

2022-04-20 12:56 UTC, skrupnyk commented on templates/build/simple-list-base.build.hbs
>        <textarea class="form-control" rows="1" placeholder="Type comment" data-comment-body></textarea>
`placeholder="{{T "widgets.list.dynamic.comments.placeholder"}}"`

2022-04-20 12:59 UTC, skrupnyk reviewed
https://github.com/Fliplet/fliplet-widget-dynamic-lists/blob/60ff1610f7476ae9751221cfa621f0bd826c19a6/js/layout-javascript/news-feed-code.js#L39

`T("widgets.list.dynamic.loading")`

2022-04-20 13:00 UTC, skrupnyk reviewed
https://github.com/Fliplet/fliplet-widget-dynamic-lists/blob/60ff1610f7476ae9751221cfa621f0bd826c19a6/js/layout-javascript/simple-list-code.js#L31

`T("widgets.list.dynamic.loading")`

2022-05-09 12:58 UTC, tonytlwu approved these changes

2022-05-16 08:33 UTC, merged